### ISSUE TITLE
Stuck in distributed training

### ISSUE THREAD

**Issue by v-nhandt21** [talkingnow/HM-Conformer#2]
Does this repo support training with 1 GPU only?

I get this error, it stuck at this step:

![image](https://github.com/talkingnow/HM-Conformer/assets/36092323/baaedb71-8a89-42cc-8036-7b1f7c053065)

**Comment by v-nhandt21** [comment]
I solve this by re-build docker

**Comment by leonardoboulitreau** [comment]
HI @v-nhandt21 , did you manage to solve this issue? I am stuck in the same place
